### PR TITLE
Sync Theme plugin topic

### LINKED ISSUE #255: Create a new topic for the Sketch plugin
Create and draft a new topic explaining how the Sketch plugin works in terms of the functionality it provides for Theming and Publishing/Syncing prototypes with the Indigo.Design Cloud.

### PR DESCRIPTION
**Pull request by DaniMarinov**
Closes #255

### CODE REVIEW

**Comment by StefanIvanov** [comment]
@DaniMarinov duplicate the new topic to jp and add it to the toc there as well. Once you do that change the label of this PR to localization-pending

**Comment by StefanIvanov** [comment]
@yoshimis could you help with the localization of this one?

**Comment by yoshimis** [comment]
@StefanIvanov Yes. I am working on it. sync-themes-plugin should be ready tomorrow.

**Comment by StefanIvanov** [comment]
> @StefanIvanov Yes. I am working on it. sync-themes-plugin should be ready tomorrow.

Oh, I thought you haven't seen it yet and wanted to make sure you are aware of it, thanks!

**Comment by StefanIvanov** [comment]
@valadzhov can you review the jp, I already have done so for the en? and then we will leave the PR until we are ready to publish the plugin and push it to production with that :)

**Pull request merged**
