### PR TITLE
Topic for what developers need to do after code generation

### PR DESCRIPTION
**Pull request by ig-robstoffers**
I wasn't sure where this topic should go so I created a new folder called codegen.  Also not sure if that name is ok.

### CODE REVIEW

**Comment by StefanIvanov** [comment]
**Looks good to me, but I think we should add the following as a header:**
---
title: ???
_description: ???
_keywords: Design System, Code Generation, Ignite UI for Angular, UI Library, Widgets ...
---

**and the following as a footer:**
## Additional Resources

Related topics:

- [Grid Filter](grid-filter.md)
  <div class="divider--half"></div>

Our community is active and always welcoming to new ideas.

- [Indigo Design **GitHub**](https://github.com/IgniteUI/design-system-docfx)
**and maybe some further external links at the bottom such as [RouterOutlet](https://angular.io/api/router/RouterOutlet)**

**Comment by ig-robstoffers** [comment]
I updated the topic.  Does that look ok?

**Comment by StefanIvanov** [comment]
Looks great, once Sarah approves as well I will merge it :)

**Comment by StefanIvanov** [comment]
and add it to the toc of course :)

**Comment by ig-robstoffers** [comment]
Was I supposed to update the toc?  If so I can do that and commit it into this pr.

**Comment by ig-ealbert** [comment]
@ig-robstoffers My reading of the comment was "I (Stefan) will merge it and add it to the TOC".  So no, I don't think you have to update the TOC.

**Pull request merged**
