### PR TITLE
better images for the layout topic

### PR DESCRIPTION
**Pull request by ig-robstoffers**

### CODE REVIEW

**Comment by StefanIvanov** [comment]
Rob it seems to me that there are more images that need to be updated. For me the most blurry one is the first image in the topic with the people app.

**Comment by ig-robstoffers** [comment]
Hmm.  I thought I replaced those but I don't see them in my pull request.  I'll commit the missing images shortly.

**Comment by ig-robstoffers** [comment]
Let me know if that is any better.

**Comment by StefanIvanov** [comment]
en looks super crisp now, once you copy the images to jp as well, I will approve the PR

**Comment by ig-robstoffers** [comment]
Sorry about that.  JP images have been updated to match the en files.

**Pull request merged**
