### PR TITLE
Update images for Indigo cloud topics

### PR DESCRIPTION
**Pull request by cbadell**
- Updating outdated images for image based designer
- Updating images for retina.
- Updating images according to new welcome message when entering an empty to workspace
- Updating images according to new visual design for hotspots.

### CODE REVIEW

**Comment by valadzhov** [comment]
@StefanIvanov I will be taking care of the JP images. Is it OK if I add them to Claudia's branch?

**Comment by StefanIvanov** [comment]
Yes @valadzhov please do :) I added the necessary labels :)

**Comment by valadzhov** [comment]
Thank you @StefanIvanov !

**Comment by StefanIvanov** [comment]
@cbadell you have one image that is too wide creating_a_prototype_9
screen shot 2019-02-21 at 2 51 35 pm

**Comment by StefanIvanov** [comment]
@valadzhov we have the problem with the image above on JP as well 
screen shot 2019-02-21 at 2 54 58 pm

and with a further one creating_a_prototype_2
screen shot 2019-02-21 at 2 54 50 pm

**Comment by valadzhov** [comment]
@StefanIvanov, right now creating_a_prototype_2 is 1440x822 (and @2x is 2880x1643)
creating_a_prototype_9 is 1440x405 (@2x is 2880x810). How much should we scale these images?

**Comment by cbadell** [comment]
@StefanIvanov shouldn't images fit the area according to the display area? How does it works when entering to the help center in mobile? Is is not responsive? Which is the maximum width that images can have at the help center? Thanks.

**Comment by StefanIvanov** [comment]
Max image width for docfx documentation is 800px (1600px on retina)

**Comment by cbadell** [comment]
@StefanIvanov thanks for sending the maximum width. I guess that means that images at the help center are not responsive. Is it in the backlog? Thanks.

**Comment by StefanIvanov** [comment]
I haven't looked into it but I think it is safe to assume so :)

**Comment by cbadell** [comment]
I will add it as an issue, so we can follow up it later.

**Comment by cbadell** [comment]
Submitted [here](https://github.com/IgniteUI/indigo-design-docfx/issues/266) the issue. 

Pablo noticed that setting `max-width: 100% ` for images at the css file makes all images responsive, and there is no need to update images files :) 

@StefanIvanov @zdrawku I think it worth to fix it at igniteui-docfx-template. What do you think? If it so, who can fix it? Thanks!

**Comment by StefanIvanov** [comment]
Claudia in the meantime if you want to push this update while the fix is applied, please replace the images with ones that would work in terms of size with the current implementation :)

**Comment by zdrawku** [comment]
We are going to make the fix later today

**Comment by zdrawku** [comment]
@cbadell Tihomir applied the requested changes in this [PR](https://github.com/IgniteUI/indigo-design-docfx/pull/267)

**Comment by cbadell** [comment]
@StefanIvanov could you please check that after the fix the images are correctly displayed, and if it so, please approve the PR. Thanks!

**Pull request merged**
