### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by StefanIvanov**
I have updated the version of some packages indicated by github as security vulnerabilities

### CODE REVIEW

**Comment by StefanIvanov** [comment]
@cbadell reminding

**Comment by HristoP96** [comment]
Every works fine as I see. 
However i think some of the dependencies must be devDependencies

**Comment by StefanIvanov** [comment]
@HristoP96 I ran the updates locally, but do we need to run them elsewhere as well. I am not very familiar with this part of the process :)

**Comment by HristoP96** [comment]
@StefanIvanov If locally the docfx works then everything is fine.  As I see this PR is ok :)

**Pull request merged**
